### ISSUE TITLE
Upload Logo

### ISSUE THREAD

**Issue by francesco-vannini** [PiSupply/Gert-VGA-666#1]
![gertvga](https://user-images.githubusercontent.com/16068311/30545226-eac87d6e-9c80-11e7-84fc-59aa8eae7669.png)

**Comment by francesco-vannini** [comment]
Use this thread to add pictures

**Comment by ChristopherRush** [comment]
![pisupply-gert-vga-github-banner](https://user-images.githubusercontent.com/1878314/73882099-6448c000-4859-11ea-88d7-2363b44d9596.png)
